baseURL: "https://leesakAn.github.io/" 
title: Leesak An
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2 
        - name: Books
          url: books/
          weight: 3
        - name: Projects
          url: projects/
          weight: 4
        - name: Experience
          url: experience/
          weight: 5

params:
    description: "This website hosts Leesak An's research papers, books, experience, curriculum vitae, and contact information."
    author: Leesak An
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","experience"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Leesak An
          subtitle: |
            Hello, I’m a student studying political science. I recently completed my M.A. at Korea University and currently work as a research staffer at the Peace & Democracy Institute. 
            
            I focus on political behavior and public opinion, with attention to identity and gender politics. 
          
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Books
              url: books/
            - name: Projects
              url: projects/
            - name: Experience
              url: experience/

    socialIcons:
        - name: CV
          url: CV_leesak(0401).pdf
        - name: Email
          url: mailto:isaac30421@gmail.com
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Leesak An"
      icon: plant.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2